
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="<?=$page->meta_desc;?>" />

<!-- //* Favicons */ -->
<link rel="apple-touch-icon" sizes="180x180" href="<?=$favIconsPath?>apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="<?=$favIconsPath?>favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?=$favIconsPath?>favicon-16x16.png">
<link rel="manifest" href="<?=$favIconsPath?>site.webmanifest">
<link rel="mask-icon" href="<?=$favIconsPath?>safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="<?=$favIconsPath?>favicon.ico">
<meta name="msapplication-TileColor" content="#000000">
<meta name="msapplication-config" content="<?=$favIconsPath?>browserconfig.xml">
<meta name="theme-color" content="#000000">

<!-- //* Phosphor Icons */ -->
<link rel="stylesheet" href="<?=$imagesPath?>/icons/phosphor/src/duotone/style.css">

<link rel="stylesheet" type="text/css" href="<?=$cssPath?>global.css" />