
<div class="allStationaryGrad top"></div>

<?php

	include("./includes/func/game-card-filters.inc");

	$maxCards = 500;

	include("./includes/func/game-card-gen.inc");

?>

<?php  ?>

<div class="allStationaryGrad bot"></div>


<div class="modal trailer-modal">
   <div class="modal-content">
      <div class="modalHeader">
         <span class="close">×</span>        
         <h3></h3>
      </div>
      <div class="modal-body">
      	<div class="trailer-responsive">
	      	<video width="320" height="240" controls autoplay="autoplay" mute="true">
			  <source type="video/mp4">		  		 
			</video>
      	</div>
      </div>
   </div>
</div>